// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common_proto/mysql_database_test.proto

#include "mysql_database_test.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr database_node_db::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : db_host_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        db_user_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        db_password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        db_dbname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0u},
        db_port_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR database_node_db::database_node_db(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct database_node_dbDefaultTypeInternal {
  PROTOBUF_CONSTEXPR database_node_dbDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~database_node_dbDefaultTypeInternal() {}
  union {
    database_node_db _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 database_node_dbDefaultTypeInternal _database_node_db_default_instance_;

inline constexpr account_database_one_test::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : account_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR account_database_one_test::account_database_one_test(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct account_database_one_testDefaultTypeInternal {
  PROTOBUF_CONSTEXPR account_database_one_testDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~account_database_one_testDefaultTypeInternal() {}
  union {
    account_database_one_test _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 account_database_one_testDefaultTypeInternal _account_database_one_test_default_instance_;

inline constexpr account_database_all_test::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : account_password_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR account_database_all_test::account_database_all_test(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct account_database_all_testDefaultTypeInternal {
  PROTOBUF_CONSTEXPR account_database_all_testDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~account_database_all_testDefaultTypeInternal() {}
  union {
    account_database_all_test _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 account_database_all_testDefaultTypeInternal _account_database_all_test_default_instance_;
static ::_pb::Metadata file_level_metadata_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto[3];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto = nullptr;
const ::uint32_t TableStruct_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::account_database_one_test, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::account_database_one_test, _impl_.account_),
    PROTOBUF_FIELD_OFFSET(::account_database_one_test, _impl_.password_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::database_node_db, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::database_node_db, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::database_node_db, _impl_.db_host_),
    PROTOBUF_FIELD_OFFSET(::database_node_db, _impl_.db_user_),
    PROTOBUF_FIELD_OFFSET(::database_node_db, _impl_.db_password_),
    PROTOBUF_FIELD_OFFSET(::database_node_db, _impl_.db_dbname_),
    PROTOBUF_FIELD_OFFSET(::database_node_db, _impl_.db_port_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::account_database_all_test, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::account_database_all_test, _impl_.account_password_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::account_database_one_test)},
        {10, -1, -1, sizeof(::database_node_db)},
        {24, -1, -1, sizeof(::account_database_all_test)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_account_database_one_test_default_instance_._instance,
    &::_database_node_db_default_instance_._instance,
    &::_account_database_all_test_default_instance_._instance,
};
const char descriptor_table_protodef_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n&common_proto/mysql_database_test.proto"
    "\032\rdb_base.proto\"h\n\031account_database_one_"
    "test\022\017\n\007account\030\001 \001(\t\022\020\n\010password\030\002 \001(\t:"
    "(\212\265\030\031account_database_one_test\222\265\030\007accoun"
    "t\"\233\001\n\020database_node_db\022\n\n\002id\030\001 \001(\r\022\017\n\007db"
    "_host\030\002 \001(\t\022\017\n\007db_user\030\003 \001(\t\022\023\n\013db_passw"
    "ord\030\004 \001(\t\022\021\n\tdb_dbname\030\005 \001(\t\022\017\n\007db_port\030"
    "\006 \001(\r: \212\265\030\020database_node_db\222\265\030\002id\262\265\030\002id\""
    "Q\n\031account_database_all_test\0224\n\020account_"
    "password\030\001 \003(\0132\032.account_database_one_te"
    "stB\tZ\007pb/gameb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_deps[1] =
    {
        &::descriptor_table_db_5fbase_2eproto,
};
static ::absl::once_flag descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto = {
    false,
    false,
    421,
    descriptor_table_protodef_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto,
    "common_proto/mysql_database_test.proto",
    &descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_once,
    descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto::offsets,
    file_level_metadata_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto,
    file_level_enum_descriptors_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto,
    file_level_service_descriptors_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_getter() {
  return &descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto(&descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto);
// ===================================================================

class account_database_one_test::_Internal {
 public:
};

account_database_one_test::account_database_one_test(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:account_database_one_test)
}
inline PROTOBUF_NDEBUG_INLINE account_database_one_test::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : account_(arena, from.account_),
        password_(arena, from.password_),
        _cached_size_{0} {}

account_database_one_test::account_database_one_test(
    ::google::protobuf::Arena* arena,
    const account_database_one_test& from)
    : ::google::protobuf::Message(arena) {
  account_database_one_test* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:account_database_one_test)
}
inline PROTOBUF_NDEBUG_INLINE account_database_one_test::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : account_(arena),
        password_(arena),
        _cached_size_{0} {}

inline void account_database_one_test::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
account_database_one_test::~account_database_one_test() {
  // @@protoc_insertion_point(destructor:account_database_one_test)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void account_database_one_test::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.account_.Destroy();
  _impl_.password_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void account_database_one_test::Clear() {
// @@protoc_insertion_point(message_clear_start:account_database_one_test)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_.ClearToEmpty();
  _impl_.password_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* account_database_one_test::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 49, 2> account_database_one_test::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_account_database_one_test_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string password = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(account_database_one_test, _impl_.password_)}},
    // string account = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(account_database_one_test, _impl_.account_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string account = 1;
    {PROTOBUF_FIELD_OFFSET(account_database_one_test, _impl_.account_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string password = 2;
    {PROTOBUF_FIELD_OFFSET(account_database_one_test, _impl_.password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\7\10\0\0\0\0\0"
    "account_database_one_test"
    "account"
    "password"
  }},
};

::uint8_t* account_database_one_test::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:account_database_one_test)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string account = 1;
  if (!this->_internal_account().empty()) {
    const std::string& _s = this->_internal_account();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "account_database_one_test.account");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string password = 2;
  if (!this->_internal_password().empty()) {
    const std::string& _s = this->_internal_password();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "account_database_one_test.password");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:account_database_one_test)
  return target;
}

::size_t account_database_one_test::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:account_database_one_test)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string account = 1;
  if (!this->_internal_account().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_account());
  }

  // string password = 2;
  if (!this->_internal_password().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_password());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData account_database_one_test::_class_data_ = {
    account_database_one_test::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* account_database_one_test::GetClassData() const {
  return &_class_data_;
}

void account_database_one_test::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<account_database_one_test*>(&to_msg);
  auto& from = static_cast<const account_database_one_test&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:account_database_one_test)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_account().empty()) {
    _this->_internal_set_account(from._internal_account());
  }
  if (!from._internal_password().empty()) {
    _this->_internal_set_password(from._internal_password());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void account_database_one_test::CopyFrom(const account_database_one_test& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:account_database_one_test)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool account_database_one_test::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* account_database_one_test::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void account_database_one_test::InternalSwap(account_database_one_test* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_, &other->_impl_.account_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
}

::google::protobuf::Metadata account_database_one_test::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_getter, &descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_once,
      file_level_metadata_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto[0]);
}
// ===================================================================

class database_node_db::_Internal {
 public:
};

database_node_db::database_node_db(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:database_node_db)
}
inline PROTOBUF_NDEBUG_INLINE database_node_db::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : db_host_(arena, from.db_host_),
        db_user_(arena, from.db_user_),
        db_password_(arena, from.db_password_),
        db_dbname_(arena, from.db_dbname_),
        _cached_size_{0} {}

database_node_db::database_node_db(
    ::google::protobuf::Arena* arena,
    const database_node_db& from)
    : ::google::protobuf::Message(arena) {
  database_node_db* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, db_port_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::db_port_));

  // @@protoc_insertion_point(copy_constructor:database_node_db)
}
inline PROTOBUF_NDEBUG_INLINE database_node_db::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : db_host_(arena),
        db_user_(arena),
        db_password_(arena),
        db_dbname_(arena),
        _cached_size_{0} {}

inline void database_node_db::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, db_port_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::db_port_));
}
database_node_db::~database_node_db() {
  // @@protoc_insertion_point(destructor:database_node_db)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void database_node_db::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.db_host_.Destroy();
  _impl_.db_user_.Destroy();
  _impl_.db_password_.Destroy();
  _impl_.db_dbname_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void database_node_db::Clear() {
// @@protoc_insertion_point(message_clear_start:database_node_db)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.db_host_.ClearToEmpty();
  _impl_.db_user_.ClearToEmpty();
  _impl_.db_password_.ClearToEmpty();
  _impl_.db_dbname_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.db_port_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.db_port_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* database_node_db::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 59, 2> database_node_db::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_database_node_db_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(database_node_db, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.id_)}},
    // string db_host = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_host_)}},
    // string db_user = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_user_)}},
    // string db_password = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_password_)}},
    // string db_dbname = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_dbname_)}},
    // uint32 db_port = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(database_node_db, _impl_.db_port_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_port_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 id = 1;
    {PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string db_host = 2;
    {PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_host_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string db_user = 3;
    {PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_user_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string db_password = 4;
    {PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string db_dbname = 5;
    {PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_dbname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 db_port = 6;
    {PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\20\0\7\7\13\11\0\0"
    "database_node_db"
    "db_host"
    "db_user"
    "db_password"
    "db_dbname"
  }},
};

::uint8_t* database_node_db::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:database_node_db)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_id(), target);
  }

  // string db_host = 2;
  if (!this->_internal_db_host().empty()) {
    const std::string& _s = this->_internal_db_host();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "database_node_db.db_host");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string db_user = 3;
  if (!this->_internal_db_user().empty()) {
    const std::string& _s = this->_internal_db_user();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "database_node_db.db_user");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string db_password = 4;
  if (!this->_internal_db_password().empty()) {
    const std::string& _s = this->_internal_db_password();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "database_node_db.db_password");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string db_dbname = 5;
  if (!this->_internal_db_dbname().empty()) {
    const std::string& _s = this->_internal_db_dbname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "database_node_db.db_dbname");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // uint32 db_port = 6;
  if (this->_internal_db_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this->_internal_db_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:database_node_db)
  return target;
}

::size_t database_node_db::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:database_node_db)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string db_host = 2;
  if (!this->_internal_db_host().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_db_host());
  }

  // string db_user = 3;
  if (!this->_internal_db_user().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_db_user());
  }

  // string db_password = 4;
  if (!this->_internal_db_password().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_db_password());
  }

  // string db_dbname = 5;
  if (!this->_internal_db_dbname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_db_dbname());
  }

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_id());
  }

  // uint32 db_port = 6;
  if (this->_internal_db_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_db_port());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData database_node_db::_class_data_ = {
    database_node_db::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* database_node_db::GetClassData() const {
  return &_class_data_;
}

void database_node_db::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<database_node_db*>(&to_msg);
  auto& from = static_cast<const database_node_db&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:database_node_db)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_db_host().empty()) {
    _this->_internal_set_db_host(from._internal_db_host());
  }
  if (!from._internal_db_user().empty()) {
    _this->_internal_set_db_user(from._internal_db_user());
  }
  if (!from._internal_db_password().empty()) {
    _this->_internal_set_db_password(from._internal_db_password());
  }
  if (!from._internal_db_dbname().empty()) {
    _this->_internal_set_db_dbname(from._internal_db_dbname());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_db_port() != 0) {
    _this->_internal_set_db_port(from._internal_db_port());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void database_node_db::CopyFrom(const database_node_db& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:database_node_db)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool database_node_db::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* database_node_db::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void database_node_db::InternalSwap(database_node_db* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.db_host_, &other->_impl_.db_host_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.db_user_, &other->_impl_.db_user_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.db_password_, &other->_impl_.db_password_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.db_dbname_, &other->_impl_.db_dbname_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.db_port_)
      + sizeof(database_node_db::_impl_.db_port_)
      - PROTOBUF_FIELD_OFFSET(database_node_db, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata database_node_db::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_getter, &descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_once,
      file_level_metadata_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto[1]);
}
// ===================================================================

class account_database_all_test::_Internal {
 public:
};

account_database_all_test::account_database_all_test(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:account_database_all_test)
}
inline PROTOBUF_NDEBUG_INLINE account_database_all_test::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : account_password_{visibility, arena, from.account_password_},
        _cached_size_{0} {}

account_database_all_test::account_database_all_test(
    ::google::protobuf::Arena* arena,
    const account_database_all_test& from)
    : ::google::protobuf::Message(arena) {
  account_database_all_test* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:account_database_all_test)
}
inline PROTOBUF_NDEBUG_INLINE account_database_all_test::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : account_password_{visibility, arena},
        _cached_size_{0} {}

inline void account_database_all_test::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
account_database_all_test::~account_database_all_test() {
  // @@protoc_insertion_point(destructor:account_database_all_test)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void account_database_all_test::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void account_database_all_test::Clear() {
// @@protoc_insertion_point(message_clear_start:account_database_all_test)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_password_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* account_database_all_test::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> account_database_all_test::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_account_database_all_test_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .account_database_one_test account_password = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(account_database_all_test, _impl_.account_password_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .account_database_one_test account_password = 1;
    {PROTOBUF_FIELD_OFFSET(account_database_all_test, _impl_.account_password_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::account_database_one_test>()},
  }}, {{
  }},
};

::uint8_t* account_database_all_test::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:account_database_all_test)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .account_database_one_test account_password = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_account_password_size()); i < n; i++) {
    const auto& repfield = this->_internal_account_password().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:account_database_all_test)
  return target;
}

::size_t account_database_all_test::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:account_database_all_test)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .account_database_one_test account_password = 1;
  total_size += 1UL * this->_internal_account_password_size();
  for (const auto& msg : this->_internal_account_password()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData account_database_all_test::_class_data_ = {
    account_database_all_test::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* account_database_all_test::GetClassData() const {
  return &_class_data_;
}

void account_database_all_test::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<account_database_all_test*>(&to_msg);
  auto& from = static_cast<const account_database_all_test&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:account_database_all_test)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_account_password()->MergeFrom(
      from._internal_account_password());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void account_database_all_test::CopyFrom(const account_database_all_test& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:account_database_all_test)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool account_database_all_test::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* account_database_all_test::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void account_database_all_test::InternalSwap(account_database_all_test* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.account_password_.InternalSwap(&other->_impl_.account_password_);
}

::google::protobuf::Metadata account_database_all_test::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_getter, &descriptor_table_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto_once,
      file_level_metadata_common_5fproto_2fmysql_5fdatabase_5ftest_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
